[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "discord-ws"
description = "A bare-bones Python wrapper for the Discord Gateway API."
requires-python = ">=3.11"
authors = [{ name = "thegamecracks" }]
readme = "README.md"
dynamic = ["version"]
dependencies = []

[tool.setuptools.dynamic]
version = { attr = "thestarboard.__version__" }
