name: Lint with Pyright

on:
  push:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        cache: pip
        cache-dependency-path: pyproject.toml
        python-version-file: pyproject.toml
    - run: pip install pyright
    - run: pip install .[tests]
    - run: pyright
